import { Metadata } from "next";
import NavBar from "./_components/NavBar";

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js 14 Learn",
    default: "Next.js 14 Learn",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
